apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-logic
  labels:
    app: orchestrator-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherfx
  template:
    metadata:
      labels:
        app: etherfx
    spec:
      containers:
      - name: etherfx-orchestrator
        image: gcr.io/high-codex-238017/etherfx-orchestrator:v9
        ports:
        - containerPort: 50051
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: orchestrator-service
spec: 
  ports:
  - port: 50051
    targetPort: 50051
  selector: 
    app: etherfx
  type: LoadBalancer