apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: gcr.io/groupify-201122/etherfx-redis:v1
        ports:
        - containerPort: 6379
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: orchestrator-redis-service
spec: 
  ports:
  - port: 6379
    targetPort: 6379
  selector: 
    app: redis
  type: LoadBalancer