# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskMetadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TaskCommon_pb2 as TaskCommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskMetadata.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12TaskMetadata.proto\x1a\x10TaskCommon.proto\"o\n\x0cTaskMetadata\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x10\n\x08\x66unction\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x05\x12\x0e\n\x06kwargs\x18\x04 \x03(\t\x12\x0f\n\x07task_id\x18\x05 \x01(\t\x12\x0e\n\x06_class\x18\x06 \x01(\t\"8\n\x0cTaskReceived\x12\x17\n\x06status\x18\x01 \x01(\x0b\x32\x07.Status\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"s\n\x10\x41rgumentMetadata\x12\x1f\n\x08\x61rg_type\x18\x01 \x01(\x0e\x32\r.ArgumentType\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x12\r\n\x03num\x18\x04 \x01(\x05H\x00\x42\x0e\n\x0c\x61rg_sequence\"O\n\x0cTaskArgument\x12$\n\x07\x61rg_seq\x18\x01 \x01(\x0b\x32\x11.ArgumentMetadataH\x00\x12\r\n\x03\x61rg\x18\x02 \x01(\x0cH\x00\x42\n\n\x08task_arg\"\"\n\x0f\x45xecTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"L\n\x0cTaskResponse\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\x07.StatusH\x00\x12\x10\n\x06result\x18\x02 \x01(\x0cH\x00\x42\x0f\n\rtask_response*2\n\x0c\x41rgumentType\x12\x0c\n\x08\x41RGUMENT\x10\x00\x12\x14\n\x10KEYWORD_ARGUMENT\x10\x01\x62\x06proto3')
  ,
  dependencies=[TaskCommon__pb2.DESCRIPTOR,])

_ARGUMENTTYPE = _descriptor.EnumDescriptor(
  name='ArgumentType',
  full_name='ArgumentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARGUMENT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYWORD_ARGUMENT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=523,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_ARGUMENTTYPE)

ArgumentType = enum_type_wrapper.EnumTypeWrapper(_ARGUMENTTYPE)
ARGUMENT = 0
KEYWORD_ARGUMENT = 1



_TASKMETADATA = _descriptor.Descriptor(
  name='TaskMetadata',
  full_name='TaskMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='TaskMetadata.module', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='function', full_name='TaskMetadata.function', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='TaskMetadata.args', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='TaskMetadata.kwargs', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='TaskMetadata.task_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_class', full_name='TaskMetadata._class', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=151,
)


_TASKRECEIVED = _descriptor.Descriptor(
  name='TaskReceived',
  full_name='TaskReceived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TaskReceived.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='TaskReceived.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=209,
)


_ARGUMENTMETADATA = _descriptor.Descriptor(
  name='ArgumentMetadata',
  full_name='ArgumentMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg_type', full_name='ArgumentMetadata.arg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ArgumentMetadata.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ArgumentMetadata.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='ArgumentMetadata.num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='arg_sequence', full_name='ArgumentMetadata.arg_sequence',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=211,
  serialized_end=326,
)


_TASKARGUMENT = _descriptor.Descriptor(
  name='TaskArgument',
  full_name='TaskArgument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg_seq', full_name='TaskArgument.arg_seq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg', full_name='TaskArgument.arg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='task_arg', full_name='TaskArgument.task_arg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=328,
  serialized_end=407,
)


_EXECTASKREQUEST = _descriptor.Descriptor(
  name='ExecTaskRequest',
  full_name='ExecTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ExecTaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=443,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TaskResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='TaskResponse.result', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='task_response', full_name='TaskResponse.task_response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=445,
  serialized_end=521,
)

_TASKRECEIVED.fields_by_name['status'].message_type = TaskCommon__pb2._STATUS
_ARGUMENTMETADATA.fields_by_name['arg_type'].enum_type = _ARGUMENTTYPE
_ARGUMENTMETADATA.oneofs_by_name['arg_sequence'].fields.append(
  _ARGUMENTMETADATA.fields_by_name['name'])
_ARGUMENTMETADATA.fields_by_name['name'].containing_oneof = _ARGUMENTMETADATA.oneofs_by_name['arg_sequence']
_ARGUMENTMETADATA.oneofs_by_name['arg_sequence'].fields.append(
  _ARGUMENTMETADATA.fields_by_name['num'])
_ARGUMENTMETADATA.fields_by_name['num'].containing_oneof = _ARGUMENTMETADATA.oneofs_by_name['arg_sequence']
_TASKARGUMENT.fields_by_name['arg_seq'].message_type = _ARGUMENTMETADATA
_TASKARGUMENT.oneofs_by_name['task_arg'].fields.append(
  _TASKARGUMENT.fields_by_name['arg_seq'])
_TASKARGUMENT.fields_by_name['arg_seq'].containing_oneof = _TASKARGUMENT.oneofs_by_name['task_arg']
_TASKARGUMENT.oneofs_by_name['task_arg'].fields.append(
  _TASKARGUMENT.fields_by_name['arg'])
_TASKARGUMENT.fields_by_name['arg'].containing_oneof = _TASKARGUMENT.oneofs_by_name['task_arg']
_TASKRESPONSE.fields_by_name['status'].message_type = TaskCommon__pb2._STATUS
_TASKRESPONSE.oneofs_by_name['task_response'].fields.append(
  _TASKRESPONSE.fields_by_name['status'])
_TASKRESPONSE.fields_by_name['status'].containing_oneof = _TASKRESPONSE.oneofs_by_name['task_response']
_TASKRESPONSE.oneofs_by_name['task_response'].fields.append(
  _TASKRESPONSE.fields_by_name['result'])
_TASKRESPONSE.fields_by_name['result'].containing_oneof = _TASKRESPONSE.oneofs_by_name['task_response']
DESCRIPTOR.message_types_by_name['TaskMetadata'] = _TASKMETADATA
DESCRIPTOR.message_types_by_name['TaskReceived'] = _TASKRECEIVED
DESCRIPTOR.message_types_by_name['ArgumentMetadata'] = _ARGUMENTMETADATA
DESCRIPTOR.message_types_by_name['TaskArgument'] = _TASKARGUMENT
DESCRIPTOR.message_types_by_name['ExecTaskRequest'] = _EXECTASKREQUEST
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.enum_types_by_name['ArgumentType'] = _ARGUMENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskMetadata = _reflection.GeneratedProtocolMessageType('TaskMetadata', (_message.Message,), dict(
  DESCRIPTOR = _TASKMETADATA,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:TaskMetadata)
  ))
_sym_db.RegisterMessage(TaskMetadata)

TaskReceived = _reflection.GeneratedProtocolMessageType('TaskReceived', (_message.Message,), dict(
  DESCRIPTOR = _TASKRECEIVED,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:TaskReceived)
  ))
_sym_db.RegisterMessage(TaskReceived)

ArgumentMetadata = _reflection.GeneratedProtocolMessageType('ArgumentMetadata', (_message.Message,), dict(
  DESCRIPTOR = _ARGUMENTMETADATA,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:ArgumentMetadata)
  ))
_sym_db.RegisterMessage(ArgumentMetadata)

TaskArgument = _reflection.GeneratedProtocolMessageType('TaskArgument', (_message.Message,), dict(
  DESCRIPTOR = _TASKARGUMENT,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:TaskArgument)
  ))
_sym_db.RegisterMessage(TaskArgument)

ExecTaskRequest = _reflection.GeneratedProtocolMessageType('ExecTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXECTASKREQUEST,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:ExecTaskRequest)
  ))
_sym_db.RegisterMessage(ExecTaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESPONSE,
  __module__ = 'TaskMetadata_pb2'
  # @@protoc_insertion_point(class_scope:TaskResponse)
  ))
_sym_db.RegisterMessage(TaskResponse)


# @@protoc_insertion_point(module_scope)
