# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TaskCommon_pb2 as TaskCommon__pb2
import TaskMetadata_pb2 as TaskMetadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskService.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11TaskService.proto\x1a\x10TaskCommon.proto\x1a\x12TaskMetadata.proto2\xbb\x01\n\x0bTaskService\x12)\n\x07\x41\x64\x64Task\x12\r.TaskMetadata\x1a\r.TaskReceived\"\x00\x12)\n\x0b\x41\x64\x64\x41rgument\x12\r.TaskArgument\x1a\x07.Status\"\x00(\x01\x12\'\n\x08\x45xecTask\x12\x10.ExecTaskRequest\x1a\x07.Status\"\x00\x12-\n\x08PollTask\x12\x10.ExecTaskRequest\x1a\r.TaskResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[TaskCommon__pb2.DESCRIPTOR,TaskMetadata__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TASKSERVICE = _descriptor.ServiceDescriptor(
  name='TaskService',
  full_name='TaskService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=60,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTask',
    full_name='TaskService.AddTask',
    index=0,
    containing_service=None,
    input_type=TaskMetadata__pb2._TASKMETADATA,
    output_type=TaskMetadata__pb2._TASKRECEIVED,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddArgument',
    full_name='TaskService.AddArgument',
    index=1,
    containing_service=None,
    input_type=TaskMetadata__pb2._TASKARGUMENT,
    output_type=TaskCommon__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExecTask',
    full_name='TaskService.ExecTask',
    index=2,
    containing_service=None,
    input_type=TaskMetadata__pb2._EXECTASKREQUEST,
    output_type=TaskCommon__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PollTask',
    full_name='TaskService.PollTask',
    index=3,
    containing_service=None,
    input_type=TaskMetadata__pb2._EXECTASKREQUEST,
    output_type=TaskMetadata__pb2._TASKRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKSERVICE)

DESCRIPTOR.services_by_name['TaskService'] = _TASKSERVICE

# @@protoc_insertion_point(module_scope)
